apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: hpd4z1gqo-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:d808d2aa87398bdcd2650aaa93a4e7553140d22e@sha256:561d6aaf4951c2ea9cc7bf352eea5e2f4b08f1f03cd188c52e9399043ee488b2
          name: container-image
